commit 1e

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,8 +7,16 @@ jobs:
     steps:
       - checkout
       - run:
+          name: Verify setup.py file
+          command: |
+            if [ ! -f synergy/synergy/setup.py ]; then
+              echo "setup.py not found!"
+              exit 1
+            fi
+      - run:
           name: Install dependencies
           command: |
+            cd synergy/synergy
             python -m pip install --upgrade pip
             pip install .
       - run:
